"""Validate project data artifacts and write a data quality report."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.data_pipeline import RAW_DATA_PATH, REQUIRED_COLUMNS, run_pipeline


PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
DASHBOARD_DATA_PATH = PROCESSED_DIR / "dashboard_county_risk.csv"
MODEL_FEATURE_TABLE_PATH = PROCESSED_DIR / "model_feature_table.csv"
REPORT_PATH = PROJECT_ROOT / "reports" / "data_quality_report.md"


MARYLAND_COUNTY_FIPS = {
    "24001",
    "24003",
    "24005",
    "24009",
    "24011",
    "24013",
    "24015",
    "24017",
    "24019",
    "24021",
    "24023",
    "24025",
    "24027",
    "24029",
    "24031",
    "24033",
    "24035",
    "24037",
    "24039",
    "24041",
    "24043",
    "24045",
    "24047",
    "24510",
}


REQUIRED_DASHBOARD_COLUMNS = {
    "county_fips",
    "county_name",
    "access_risk_score",
    "access_risk_tier",
    "top_risk_factor",
    "provider_gap_index",
    "socioeconomic_need_index",
    "chronic_burden_index",
    "hospital_quality_gap_index",
}


def ensure_processed_data() -> pd.DataFrame:
    if not DASHBOARD_DATA_PATH.exists():
        run_pipeline()
    return pd.read_csv(DASHBOARD_DATA_PATH, dtype={"county_fips": str})


def validate_required_files() -> list[str]:
    required_files = [
        RAW_DATA_PATH,
        DASHBOARD_DATA_PATH,
        MODEL_FEATURE_TABLE_PATH,
        PROJECT_ROOT / "sql" / "schema.sql",
        PROJECT_ROOT / "sql" / "queries.sql",
        PROJECT_ROOT / "data" / "raw" / "maryland_counties.geojson",
    ]
    return [str(path.relative_to(PROJECT_ROOT)) for path in required_files if not path.exists()]


def validate_dataframes(raw: pd.DataFrame, processed: pd.DataFrame) -> list[str]:
    errors: list[str] = []

    missing_raw_columns = sorted(REQUIRED_COLUMNS - set(raw.columns))
    if missing_raw_columns:
        errors.append(f"Raw data missing required columns: {missing_raw_columns}")

    missing_processed_columns = sorted(REQUIRED_DASHBOARD_COLUMNS - set(processed.columns))
    if missing_processed_columns:
        errors.append(f"Processed data missing required columns: {missing_processed_columns}")

    fips = set(processed["county_fips"].astype(str).str.zfill(5))
    missing_counties = sorted(MARYLAND_COUNTY_FIPS - fips)
    extra_counties = sorted(fips - MARYLAND_COUNTY_FIPS)
    if missing_counties:
        errors.append(f"Processed data missing Maryland county FIPS: {missing_counties}")
    if extra_counties:
        errors.append(f"Processed data contains unexpected FIPS: {extra_counties}")

    duplicate_counties = processed.duplicated(["county_fips", "data_year"]).sum()
    if duplicate_counties:
        errors.append(f"Processed data has {duplicate_counties} duplicate county/year rows")

    if not processed["access_risk_score"].between(0, 100).all():
        errors.append("Access risk scores must be between 0 and 100")

    component_columns = [
        "provider_gap_index",
        "socioeconomic_need_index",
        "chronic_burden_index",
        "hospital_quality_gap_index",
    ]
    for column in component_columns:
        if not processed[column].between(0, 100).all():
            errors.append(f"{column} values must be between 0 and 100")

    return errors


def build_report(raw: pd.DataFrame, processed: pd.DataFrame, errors: list[str]) -> str:
    missingness = processed.isna().sum()
    missingness_lines = [
        f"- `{column}`: {int(count)} missing values"
        for column, count in missingness.items()
        if int(count) > 0
    ]
    if not missingness_lines:
        missingness_lines = ["- No missing values detected in processed dashboard data."]

    duplicate_count = int(processed.duplicated(["county_fips", "data_year"]).sum())
    risk_min = processed["access_risk_score"].min()
    risk_max = processed["access_risk_score"].max()
    tier_counts = processed["access_risk_tier"].value_counts().to_dict()

    status = "PASS" if not errors else "REVIEW REQUIRED"
    error_lines = [f"- {error}" for error in errors] or ["- No validation errors detected."]

    return f"""# Data Quality Report

## Validation Status

**Status:** {status}

## Source Coverage

- Raw sample file: `data/raw/maryland_county_health_access_sample.csv`
- County boundary file: `data/raw/maryland_counties.geojson`
- Processed dashboard file: `data/processed/dashboard_county_risk.csv`
- SQLite database generated by `src/data_pipeline.py`

The current dataset is a portfolio demonstration sample. It is structured to mirror official public data sources, but it is not an official public-health extract.

## Row Counts

- Raw rows: {len(raw)}
- Processed rows: {len(processed)}
- Expected Maryland county/county-equivalent rows: {len(MARYLAND_COUNTY_FIPS)}

## County Coverage

- Unique processed county FIPS codes: {processed["county_fips"].nunique()}
- County coverage complete: {processed["county_fips"].nunique() == len(MARYLAND_COUNTY_FIPS)}

## Missingness

{chr(10).join(missingness_lines)}

## Duplicate Checks

- Duplicate county/year rows: {duplicate_count}

## Feature Range Checks

- Access risk score range: {risk_min:.1f} to {risk_max:.1f}
- Risk score within 0-100: {processed["access_risk_score"].between(0, 100).all()}
- Risk tier counts: {tier_counts}

## Validation Findings

{chr(10).join(error_lines)}

## Known Limitations

- The data values are illustrative and should not be used for operational public-health decisions.
- County-level averages may hide neighborhood-level variation.
- The model target may use an external-proxy sample field or a demonstration score-derived label, depending on `src/risk_model.py` target mode.
- A production version should add official source extracts, extract dates, table IDs, and automated data quality checks by source.
"""


def validate_project(write_report: bool = True) -> list[str]:
    raw = pd.read_csv(RAW_DATA_PATH, dtype={"county_fips": str})
    processed = ensure_processed_data()

    errors = validate_required_files()
    errors.extend(validate_dataframes(raw, processed))

    if write_report:
        REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        REPORT_PATH.write_text(build_report(raw, processed, errors), encoding="utf-8")

    return errors


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-report", action="store_true", help="Validate without writing a report.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    errors = validate_project(write_report=not args.no_report)
    if errors:
        print("Data validation failed:")
        for error in errors:
            print(f"- {error}")
        raise SystemExit(1)
    print(f"Data validation passed. Report: {REPORT_PATH}")


if __name__ == "__main__":
    main()
